DROP TABLE NEWS_RESULT; 
CREATE TABLE NEWS_RESULT
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
title VARCHAR(500),
summary VARCHAR(1000),
author VARCHAR(50),
CONSTRAINT primary_key PRIMARY KEY (id)
) ;
